INSERT INTO personal (id, document_number, names, last_name, mother_last_name, birthdate, civil_status, sexo, cellphone, email, address, img_url, state, id_user, id_document) VALUES 
(1, '2', 'Froilan', 'Durand', 'Durand', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(2, '3', 'Richard', 'Garcia', 'Garcia', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(3, '4', 'Oldrin', 'Huaman', 'Huaman', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(4, '5', 'Miguel', 'Silva', 'Silva', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(5, '6', 'Yeimy', 'Flores', 'Flores', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(6, '7', 'Die', 'Reynoso', 'Reynoso', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(7, '8', 'Marcelo', 'Arroyo', 'Arroyo', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(8, '9', 'Dajhana', 'Davila', 'Davila', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(9, '10','Junior', 'Castro', 'Castro', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(10, '11','Jefferson', 'Maravi', 'Maravi', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(11, '12','Jimena', 'Lopez', 'Lopez', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(12, '13','Nayely', 'Alayo', 'Alayo', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(13, '14','Thalia', 'Pastrana', 'Pastrana', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(14, '15','Kevin', 'Tarazona', 'Tarazona', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(15, '16','Denisse', 'Andrade', 'Andrade', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(16, '17','Maria', 'Vasquez', 'Vasquez', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(17, '18','Jared', 'Pizan', 'Pizan', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(18, '19','Jorge', 'Laura', 'Laura', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(19, '20','Jean', 'Estrada', 'Estrada', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(20, '21','Luz', 'Condori', 'Condori', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(21, '22','Sergio', 'Cordova', 'Cordova', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(22, '23','Jesus', 'Peña', 'Peña', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(23, '24','Jhon', 'Cordova', 'Cordova', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(24, '25','Gustavo', 'Ricardo', 'Ricardo', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(25, '26','Milena', 'Valdez', 'Valdez', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(26, '27','Oscar', 'Valera', 'Valera', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(27, '28','Vania', 'Cusipuma', 'Cusipuma', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'CESADO', NULL, 1),
(28, '29','Ruth', 'Llaja', 'Llaja', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
(29, '30','Haans', 'Cordero', 'Cordero', NULL, NULL, NULL, '9', NULL, NULL, 'personals/user_default.png', 'ACTIVO', NULL, 1),
