<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('profits', function (Blueprint $table) {
            $table->id();
            $table->morphs('profitability'); // Creates 'profitability_id' and 'profitability_type'
            $table->unsignedBigInteger('personal_id'); // Related to the seller (vendedor)
            $table->decimal('seller_profit', 10, 2); // 50% for the seller
            $table->decimal('company_profit', 10, 2); // 50% for the company
            $table->decimal('total_profit', 10, 2); // Total profit generated by the service
            $table->timestamps();

            $table->foreign('personal_id')->references('id')->on('personal');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('profits');
    }
};
